printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: "all"
bracketSpacing: true
arrowParens: "always"
endOfLine: "lf"
plugins:
  - prettier-plugin-tailwindcss
tailwindStylesheet: ./apps/web/app/globals.css
